#!/command/with-contenv bash

cd "${HOME}"
echo "INFO: starting code-server..."
mkdir -p git

# to run poetry from vscode terminal
PATH="$HOME/.local/bin:$PATH"

exec 2>&1
exec /usr/bin/code-server \
  --bind-addr 0.0.0.0:8887 \
  --disable-telemetry \
  --disable-update-check \
  --disable-workspace-trust \
  --disable-getting-started-override \
  --auth none \
  "${HOME}"/git
